margin = 150
indent = 2
align_matrix = true
align_pair_arrow = true
align_assignment = true
align_conditional = true
align_struct_field = true
short_to_long_function_def = false
join_lines_based_on_source = true
annotate_untyped_fields_with_any = false
whitespace_ops_in_indices = true
always_for_in = true
